# Generated by Django 5.2 on 2025-04-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_instalacion', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos_proyectos/')),
            ],
        ),
    ]
