# Generated by Django 5.2 on 2025-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
