# Generated by Django 5.2 on 2025-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_imagencarrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='fotos_destacado/')),
            ],
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='direccion',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
