# Generated by Django 5.2 on 2025-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Foto exclusiva para el header de detalle', null=True, upload_to='productos/headers/'),
        ),
    ]
