import os
from pathlib import Path

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.
"""

# =========================
# Base
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# Seguridad / Debug
# =========================
# En prod SÍ o SÍ define DJANGO_SECRET_KEY en Variables (Web tab) o en WSGI env
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key")

# En PythonAnywhere deja DJANGO_DEBUG=0
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Hosts permitidos
# En prod define DJANGO_ALLOWED_HOSTS ejemplo:
# Jalann.pythonanywhere.com,www.tudominio.cl
_raw_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]

# Para desarrollo local, si no seteas nada, no te bloquea
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# CSRF trusted origins (para formularios en prod)
# En PythonAnywhere define DJANGO_CSRF_TRUSTED ejemplo:
# https://Jalann.pythonanywhere.com,https://www.tudominio.cl
_raw_csrf = os.environ.get("DJANGO_CSRF_TRUSTED", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf.split(",") if o.strip()]

# Cookies seguras en prod (recomendado)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG  # PythonAnywhere normalmente va con https

# =========================
# Apps
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "proyectos",

    # Cloudinary
    "cloudinary",
    "cloudinary_storage",
]

# =========================
# Middleware
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# =========================
# URLs / Templates / WSGI
# =========================
ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # si tienes templates globales, pon BASE_DIR / "templates"
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# =========================
# Database (MySQL PythonAnywhere)
# =========================
# Asegúrate de tener:
# MYSQL_NAME, MYSQL_USER, MYSQL_PASSWORD, MYSQL_HOST, MYSQL_PORT
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_NAME"),
        "USER": os.environ.get("MYSQL_USER"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD"),
        "HOST": os.environ.get("MYSQL_HOST"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
        "OPTIONS": {
            # Modo estricto para evitar datos raros
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
        },
    }
}

# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# i18n / TZ
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================
# Static files
# =========================
# IMPORTANTE: debe empezar con /
STATIC_URL = "/static/"

# Carpeta donde collectstatic junta todo (prod)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Tus estáticos dentro del app
STATICFILES_DIRS = [
    BASE_DIR / "proyectos" / "static",
]

# =========================
# Media / Cloudinary
# =========================
USE_CLOUDINARY = os.environ.get("USE_CLOUDINARY", "0") == "1"

# Default local media (por si Cloudinary está apagado)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if USE_CLOUDINARY:
    # Credenciales por env (mejor práctica)
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
        "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
        "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    }

    # Django 5+: usa STORAGES
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# =========================
# Default primary key
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
